import java.sql.*;

public class PostgreSQLJDBCConnection {

    public static void main(String[] args) {
        getALlStudents();
        updateStudentEmail(6, "Iambatman@gmail.com");
        getALlStudents();
        deleteStudent(6);
        getALlStudents();
    }

    /**
     * Function to retrieve all students from the database.
     */
    public static void getALlStudents() {
        // Connection details
        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "postgres";
        String password = "admin";

        try {
            Class.forName("org.postgresql.Driver"); // loads the driver for JDBC
            Connection conn = DriverManager.getConnection(url, user, password); // establishes a connection to the db using the credentials

            if (conn != null) { // checks if connection was made or not
                Statement stmt = conn.createStatement(); // Create statement
                String SQL = "SELECT * FROM students"; // The SQL query that needs to be executed
                ResultSet rs = stmt.executeQuery(SQL); // Executes the query and stores the result
                while (rs.next()) { // iterates through the result and displays each line
                    int id = rs.getInt("student_id");
                    String firstName = rs.getString("first_name");
                    String lastName = rs.getString("last_name");
                    String email = rs.getString("email");
                    String enrollmentDate = rs.getString("enrollment_date");

                    System.out.println("student_id: " + id + " first_name: " + firstName + " last_name: "
                            + lastName + " email: " + email + " enrollment_date: " + enrollmentDate);
                }
                // Close resources
                rs.close();
                stmt.close();
            } else {
                System.out.println("Failed to establish connection."); // displayed when connection was not established
            }

            // close the connection
            conn.close();

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }


    /**
     * Function to add a student to the database.
     * Requires all attributes except id(autogenerated).
     *
     * @param first_name the first name of the student
     * @param last_name the last name of the student
     * @param email the email of the student
     * @param enrollment_date the enrollment data of the student
     */
    public static void addStudent(String first_name, String last_name, String email, String enrollment_date) {
        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "postgres";
        String password = "admin";

        try {
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection(url, user, password);
            if (conn != null) {
                // The SQL query for inserting students into the table
                String insertSQL = "INSERT INTO students (first_name, last_name, email, enrollment_date) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pstmt = conn.prepareStatement(insertSQL)) { // makes a prepared statement
                    pstmt.setString(1, first_name); // inputs first name in the query
                    pstmt.setString(2, last_name); // inputs last name in the query
                    pstmt.setString(3, email); // inputs email in the query
                    pstmt.setDate(4, Date.valueOf(enrollment_date)); // inputs enrollment date in the query
                    pstmt.executeUpdate(); // executes the query
                    System.out.println("Data inserted using PreparedStatement."); // displays success of data insertion
                }
            } else {
                System.out.println("Failed to establish connection.");
            }
            conn.close();
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Function to update student email.
     * Requires student id and the new email for this student.
     *
     * @param student_id the id of the student whose email needs to be updated
     * @param new_email the new email of the student
     */
    public static void updateStudentEmail(int student_id, String new_email) {
        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "postgres";
        String password = "admin";

        try {
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection(url, user, password);
            if (conn != null) {
                // the query for updating student email
                String updateSQL = "UPDATE students SET email = ? WHERE student_id = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(updateSQL)) {
                    pstmt.setString(1, new_email);
                    pstmt.setInt(2, student_id);
                    pstmt.executeUpdate();
                    System.out.println("Data updated using PreparedStatement.");
                }
            } else {
                System.out.println("Failed to establish connection.");
            }
            conn.close();

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Function to delete student from the database.
     * Requires the student id of the student to be deleted.
     *
     * @param student_id the id of the student to be deleted
     */
    public static void deleteStudent(int student_id) {
        String url = "jdbc:postgresql://localhost:5432/postgres";
        String user = "postgres";
        String password = "admin";

        try {
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection(url, user, password);
            if (conn != null) {
                // The query for deleting a student
                String deleteSQL = "DELETE FROM students WHERE student_id = ?";
                try (PreparedStatement pstmt = conn.prepareStatement(deleteSQL)) {
                    pstmt.setInt(1, student_id);
                    pstmt.executeUpdate();
                    System.out.println("Data deleted using PreparedStatement.");
                }
            } else {
                System.out.println("Failed to establish connection.");
            }
            conn.close();

        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
    }


}

